import slide1 from "../assets/img/main/products/01.jpeg";
import slide2 from "../assets/img/main/products/02.jpeg";
import slide3 from "../assets/img/main/products/03.jpeg";

export const products = [
    {
        id: 0,
        img: slide1,
        title: "Термобілизна для бодібілдерів",
        gender: "Для чоловіків",
        value: "2 кольори",
        price: "4000 грн",
    },
    {
        id: 1,
        img: slide2,
        title: "Майка для бодібілдерів",
        gender: "Для жінок",
        value: "6 кольорів",
        price: "1100 грн",
    },
    {
        id: 2,
        img: slide3,
        title: "Ланцюжок для бодібілдерів",
        gender: "Аксесуари",
        value: "30 кг.",
        price: "2000 грн",
    },
    {
        id: 3,
        img: slide1,
        title: "Термобілизна для бодібілдерів",
        gender: "Для чоловіків",
        value: "2 кольори",
        price: "4050 грн",
    },
    {
        id: 4,
        img: slide2,
        title: "Майка для бодібілдерів",
        gender: "Для жінок",
        value: "6 кольорів",
        price: "1150 грн",
    },
    {
        id: 5,
        img: slide3,
        title: "Ланцюжок для бодібілдерів",
        gender: "Аксесуари",
        value: "30 кг.",
        price: "2050 грн",
    },
    {
        id: 6,
        img: slide1,
        title: "Термобілизна для бодібілдерів",
        gender: "Для чоловіків",
        value: "2 кольори",
        price: "4050 грн",
    },
    {
        id: 7,
        img: slide2,
        title: "Майка для бодібілдерів",
        gender: "Для жінок",
        value: "6 кольорів",
        price: "1150 грн",
    },
    {
        id: 8,
        img: slide3,
        title: "Ланцюжок для бодібілдерів",
        gender: "Аксесуари",
        value: "30 кг.",
        price: "2050 грн",
    },
    {
        id: 9,
        img: slide2,
        title: "Майка для бодібілдерів",
        gender: "Для жінок",
        value: "6 кольорів",
        price: "1159 грн",
    },
    {
        id: 10,
        img: slide3,
        title: "Ланцюжок для бодібілдерів",
        gender: "Аксесуари",
        value: "30 кг.",
        price: "2059 грн",
    },
];
